# Generated by Django 2.2.2 on 2019-07-02 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Фамилия', help_text='Как к Вам обращаться?', max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(default='Фамилия', help_text='Ваша фамилия', max_length=30, verbose_name='Фамилия')),
                ('otch_name', models.CharField(blank=True, default='', help_text='Кто Вы по батьке?', max_length=30, verbose_name='Отчество')),
                ('age', models.IntegerField(default='22', help_text='Укажите Ваш возрат', verbose_name='Возраст')),
                ('email', models.EmailField(default='example@mail.com', help_text='Укажите Вашу электронную почту', max_length=254, verbose_name='Эл. почта')),
                ('phone', models.IntegerField(default='89997776655', help_text='Телефон для связи с Вами', verbose_name='Моб. тел.')),
                ('commet', models.TextField(blank=True, default='Моё пожелание/описание одежды', help_text='Укажите свои пожелания в одежде', max_length=255, verbose_name='')),
                ('data_create', models.DateTimeField(default=datetime.datetime(2019, 7, 2, 22, 41, 59, 106860), verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Потенциальный клиент',
                'verbose_name_plural': 'Потенциальные клиенты',
            },
        ),
    ]
