# Generated by Django 2.2.2 on 2019-08-24 11:44

import app.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.UUIDField(default=uuid.uuid4)),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
            },
        ),
        migrations.CreateModel(
            name='OrderTovary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Orders')),
            ],
            options={
                'verbose_name': 'Товар Заказа',
                'verbose_name_plural': 'Товары заказов',
            },
        ),
        migrations.CreateModel(
            name='PotentialClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Фамилия', help_text='Как к Вам обращаться?', max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(default='Фамилия', help_text='Ваша фамилия', max_length=30, verbose_name='Фамилия')),
                ('otch_name', models.CharField(blank=True, default='', help_text='Кто Вы по батьке?', max_length=30, verbose_name='Отчество')),
                ('age', models.IntegerField(default='22', help_text='Укажите Ваш возрат', verbose_name='Возраст')),
                ('email', models.EmailField(default='example@mail.com', help_text='Укажите Вашу электронную почту', max_length=254, verbose_name='Эл. почта')),
                ('phone', models.IntegerField(default='89997776655', help_text='Телефон для связи с Вами', verbose_name='Моб. тел.')),
                ('commet', models.TextField(blank=True, default='Моё пожелание/описание одежды', help_text='Укажите свои пожелания в одежде', max_length=255, verbose_name='')),
                ('data_create', models.DateTimeField(default=datetime.datetime(2019, 8, 24, 16, 44, 25, 67810), verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Потенциальный клиент',
                'verbose_name_plural': 'Потенциальные клиенты',
            },
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.PositiveIntegerField(unique=True, verbose_name='Код статуса')),
                ('text', models.TextField(verbose_name='Текстовое представление статуса')),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.UUIDField(default=uuid.uuid1)),
                ('title', models.CharField(max_length=50, verbose_name='Нозвание изделия')),
                ('descr', models.TextField(verbose_name='Описание товара')),
                ('uhod', models.TextField(verbose_name='Уход за изделием')),
                ('sebestoimost', models.PositiveIntegerField(verbose_name='Себестоимость товара')),
                ('cost', models.PositiveIntegerField(default=5000, verbose_name='Цена для клиента')),
                ('data_create', models.DateField(auto_now_add=True, verbose_name='Дата добавления товара')),
                ('hidden', models.BooleanField(default=True, help_text='Признак видимости товара на сайте', verbose_name='Видимость для покупателя')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='Variaciya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.UUIDField(default=uuid.uuid4)),
                ('color', app.models.ColorField(default='#FF0000', max_length=7, verbose_name='Цвет материала')),
                ('color_text', models.CharField(default='Красный', max_length=25, verbose_name='Название цвета')),
                ('size', models.TextField(default='S', verbose_name='Размер')),
                ('obmer', models.TextField(verbose_name='Обмеры')),
                ('model', models.TextField(verbose_name='Параметры модели')),
                ('kolvo', models.SmallIntegerField(default=0, verbose_name='Количество на складах')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovars', to='app.Tovar')),
            ],
            options={
                'verbose_name': 'Вариация товара',
                'verbose_name_plural': 'Вариации товаров',
            },
        ),
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('variaciya_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Variaciya')),
                ('count', models.SmallIntegerField(verbose_name='Количество')),
                ('summ', models.SmallIntegerField(verbose_name='Сумма')),
            ],
            bases=('app.variaciya',),
        ),
        migrations.CreateModel(
            name='OrderTovaryVariaciya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('ordertovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OrderTovary')),
                ('variaciya', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Variaciya')),
            ],
            options={
                'verbose_name': 'Вариация товара',
                'verbose_name_plural': 'Выриации товаров',
            },
        ),
        migrations.AddField(
            model_name='ordertovary',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Tovar'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.StatusOrder'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='app.Variaciya')),
            ],
        ),
    ]
