# Generated by Django 2.2.2 on 2019-08-17 11:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namber', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
            },
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.PositiveIntegerField(unique=True, verbose_name='Код статуса')),
                ('text', models.TextField(verbose_name='Текстовое представление статуса')),
            ],
        ),
        migrations.CreateModel(
            name='Variaciya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('size', models.TextField(default='S', verbose_name='Размер')),
                ('obmer', models.TextField(verbose_name='Обмеры')),
                ('model', models.TextField(verbose_name='Параметры модели')),
            ],
            options={
                'verbose_name': 'Вариация товара',
                'verbose_name_plural': 'Вариации товаров',
            },
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 16, 13, 21, 855587), verbose_name='Дата регистрации'),
        ),
        migrations.CreateModel(
            name='OrderTovary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Orders')),
                ('variaciya', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Variaciya')),
            ],
            options={
                'verbose_name': 'Товар Заказа',
                'verbose_name_plural': 'Товары заказов',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.StatusOrder'),
        ),
    ]
