# Generated by Django 2.2.2 on 2019-08-24 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 16, 49, 38, 241856), verbose_name='Дата регистрации'),
        ),
    ]
