# Generated by Django 2.2.2 on 2019-08-24 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190824_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='korzina',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 17, 11, 45, 588724), verbose_name='Дата регистрации'),
        ),
    ]
