# Generated by Django 2.2.2 on 2019-08-17 12:03

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190817_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.AlterField(
            model_name='orders',
            name='namber',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 17, 3, 43, 67399), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='variaciya',
            name='article',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
