# Generated by Django 2.2.2 on 2019-08-17 12:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190817_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='cost',
            field=models.PositiveIntegerField(default=5000, verbose_name='Цена для клиента'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='data_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovar',
            name='descr',
            field=models.TextField(default="Описание", verbose_name='Описание товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovar',
            name='hidden',
            field=models.BooleanField(default=True, help_text='Признак видимости товара на сайте', verbose_name='Видимость для покупателя'),
        ),
        migrations.AddField(
            model_name='tovar',
            name='kod',
            field=models.UUIDField(default=uuid.uuid1),
        ),
        migrations.AddField(
            model_name='tovar',
            name='sebestoimost',
            field=models.PositiveIntegerField(default=0, verbose_name='Себестоимость товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovar',
            name='title',
            field=models.CharField(default="Товар", max_length=50, verbose_name='Нозвание изделия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tovar',
            name='uhod',
            field=models.TextField(default="Уход", verbose_name='Уход за изделием'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variaciya',
            name='tovar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Tovar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 17, 29, 57, 533434), verbose_name='Дата регистрации'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.Tovar')),
            ],
        ),
    ]
