# Generated by Django 2.2.2 on 2019-08-24 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190824_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 17, 13, 2, 656917), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='variaciya',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacii', to='app.Tovar'),
        ),
    ]
