# Generated by Django 2.2.2 on 2019-08-17 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190817_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertovary',
            name='count',
        ),
        migrations.RemoveField(
            model_name='ordertovary',
            name='variaciya',
        ),
        migrations.AddField(
            model_name='ordertovary',
            name='tovar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Tovar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.Variaciya'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 19, 23, 28, 950088), verbose_name='Дата регистрации'),
        ),
        migrations.CreateModel(
            name='OrderTovaryVariaciya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('ordertovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OrderTovary')),
                ('variaciya', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Variaciya')),
            ],
            options={
                'verbose_name': 'Вариация товара',
                'verbose_name_plural': 'Выриации товаров',
            },
        ),
    ]
