# Generated by Django 2.2.2 on 2019-08-17 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190817_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertovaryvariaciya',
            name='variaciya',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='variaciya', chained_model_field='variaciya', on_delete=django.db.models.deletion.CASCADE, to='app.Variaciya'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 20, 14, 37, 284906), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='variaciya',
            name='tovar',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='tovar', chained_model_field='tovar', on_delete=django.db.models.deletion.CASCADE, to='app.Tovar'),
        ),
    ]
