# Generated by Django 2.2.2 on 2019-08-25 12:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190825_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordertovary',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovary', to='app.Orders'),
        ),
        migrations.AlterField(
            model_name='ordertovary',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_orders', to='app.Tovar'),
        ),
        migrations.AlterField(
            model_name='ordertovaryvariaciya',
            name='ordertovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacii', to='app.OrderTovary'),
        ),
        migrations.AlterField(
            model_name='ordertovaryvariaciya',
            name='variaciya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_orders', to='app.Variaciya'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 25, 17, 46, 25, 477416), verbose_name='Дата регистрации'),
        ),
    ]
