# Generated by Django 2.2.2 on 2019-08-17 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190817_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 20, 51, 36, 256062), verbose_name='Дата регистрации'),
        ),
    ]
