# Generated by Django 2.2.2 on 2019-10-12 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190901_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галлерея вариации', 'verbose_name_plural': 'Галлереи вариаций'},
        ),
        migrations.AlterModelOptions(
            name='ordertovary',
            options={'verbose_name': 'Заказанное изделие', 'verbose_name_plural': 'Заказанные изделия'},
        ),
        migrations.AlterModelOptions(
            name='ordertovaryvariaciya',
            options={'verbose_name': 'Вариация товара из заявки', 'verbose_name_plural': 'Вариации товаров из заявок'},
        ),
        migrations.AlterModelOptions(
            name='statusorder',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Справочник статусов заказа'},
        ),
        migrations.AlterModelOptions(
            name='variaciya',
            options={'verbose_name': 'Вариация изделия', 'verbose_name_plural': 'Вариации изделий'},
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 12, 3, 38, 679446), verbose_name='Дата регистрации'),
        ),
    ]
