# Generated by Django 2.2.2 on 2019-08-17 16:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190817_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertovaryvariaciya',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Orders'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordertovaryvariaciya',
            name='variac',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='order', chained_model_field='order', on_delete=django.db.models.deletion.CASCADE, to='app.Variaciya'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 21, 7, 14, 140496), verbose_name='Дата регистрации'),
        ),
    ]
