# Generated by Django 2.2.2 on 2019-08-17 17:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190817_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertovaryvariaciya',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordertovaryvariaciya',
            name='variac',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='ordertovaryvariaciya',
            name='variaciya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Variaciya'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 22, 53, 0, 502167), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='variaciya',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tovar'),
        ),
    ]
