# Generated by Django 2.2.6 on 2019-11-11 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191014_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='(Например: Платья, юбки, костюмы)', max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordertovary',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordertovary',
            name='tovar',
        ),
        migrations.RemoveField(
            model_name='ordertovaryvariaciya',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordertovaryvariaciya',
            name='ordertovar',
        ),
        migrations.RemoveField(
            model_name='ordertovaryvariaciya',
            name='variaciya',
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 20, 6, 1, 368528), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название изделия'),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderTovary',
        ),
        migrations.DeleteModel(
            name='OrderTovaryVariaciya',
        ),
    ]
