# Generated by Django 2.2.6 on 2019-11-11 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191111_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 20, 9, 34, 625356), verbose_name='Дата регистрации'),
        ),
    ]
