# Generated by Django 2.2.2 on 2019-08-19 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190817_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='app.Variaciya'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 0, 34, 41, 513238), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='variaciya',
            name='article',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='variaciya',
            name='tovar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovar', to='app.Tovar'),
        ),
    ]
