# Generated by Django 2.2.2 on 2019-08-21 17:10

import app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190820_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='variaciya',
            name='color',
            field=app.models.ColorField(default='#FF0000', max_length=7, verbose_name='Цвет материала'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 22, 10, 10, 280683), verbose_name='Дата регистрации'),
        ),
    ]
