# Generated by Django 2.2.2 on 2019-08-21 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190821_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='variaciya',
            name='color_text',
            field=models.CharField(default='Красный', max_length=25, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 22, 17, 13, 751747), verbose_name='Дата регистрации'),
        ),
    ]
