# Generated by Django 2.2.2 on 2019-08-22 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190821_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korzina',
            fields=[
                ('variaciya_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.Variaciya')),
                ('count', models.SmallIntegerField(verbose_name='Количество')),
            ],
            options={
                'managed': False,
            },
            bases=('app.variaciya',),
        ),
        migrations.AddField(
            model_name='variaciya',
            name='kolvo',
            field=models.SmallIntegerField(default=0, verbose_name='Количество на складах'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 23, 20, 46, 500076), verbose_name='Дата регистрации'),
        ),
    ]
