# Generated by Django 2.2.6 on 2019-11-11 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191111_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tovaritems', to='app.Category', verbose_name='Категория товара'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 20, 26, 44, 833599), verbose_name='Дата регистрации'),
        ),
    ]
