# Generated by Django 2.2.6 on 2019-11-12 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20191111_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='tovar',
            options={'ordering': ['title'], 'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='url адресс данной категории', max_length=200),
        ),
        migrations.AddField(
            model_name='tovar',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='url адресс товара'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, help_text='(Например: Платья, юбки, костюмы)', max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 18, 11, 8, 589350), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название изделия'),
        ),
        migrations.AlterIndexTogether(
            name='tovar',
            index_together={('id', 'slug')},
        ),
    ]
