# Generated by Django 2.2.6 on 2019-12-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191112_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Краткое название коллекции. Например: "Зима-Лето 2020"', max_length=50, verbose_name='Название коллекции')),
                ('slug', models.SlugField(blank=True, help_text='url адресс данной коллекции', max_length=200, unique=True)),
                ('data_create', models.DateField(auto_now_add=True, verbose_name='Дата создания коллекции')),
                ('data_change', models.DateField(auto_now=True, verbose_name='Дата изменения коллекции')),
            ],
            options={
                'verbose_name': 'Коллекция товаров',
                'verbose_name_plural': 'Коллекции товаров',
                'ordering': ['-data_create'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='data_change',
            field=models.DateField(auto_now=True, verbose_name='Дата изменения категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='data_create',
            field=models.DateField(auto_now_add=True, default='1970-01-01', verbose_name='Дата создания категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='url адресс данной категории', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='potentialclient',
            name='data_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='url адресс товара'),
        ),
    ]
