# Generated by Django 2.2.6 on 2019-12-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0003_remove_consignment_items'),
        ('app', '0019_auto_20191222_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='variaciya',
            name='consignments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_consignments', to='fabricator.consignment'),
            preserve_default=False,
        ),
    ]
