# Generated by Django 2.2.6 on 2020-01-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_variaciya_consignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variaciya',
            name='consignments',
        ),
    ]
