# Generated by Django 2.2.6 on 2020-01-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0003_remove_consignment_items'),
        ('app', '0021_remove_variaciya_consignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='variaciya',
            name='consignments',
            field=models.ManyToManyField(related_name='in_consignments', to='fabricator.consignment'),
        ),
    ]
