# Generated by Django 2.2.6 on 2020-01-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0007_auto_20200108_1814'),
        ('app', '0023_remove_variaciya_consignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='variaciya',
            name='consignments',
            field=models.ManyToManyField(to='fabricator.consignment'),
        ),
    ]
