# Generated by Django 2.2.6 on 2020-01-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0007_auto_20200108_1814'),
        ('app', '0024_variaciya_consignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtoM_VarsToCons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolvo', models.SmallIntegerField(default=0, verbose_name='Количество')),
                ('consignments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_consignments', to='fabricator.consignment')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_gallery', to='app.Gallery')),
                ('variacii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_variacii', to='app.Variaciya')),
            ],
        ),
    ]
