# Generated by Django 2.2.6 on 2020-01-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200109_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variaciya',
            name='kolvo',
        ),
    ]
