# Generated by Django 2.2.6 on 2020-01-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_statusorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Фото вариации', 'verbose_name_plural': 'Фотографии вариации'},
        ),
        migrations.AddField(
            model_name='variaciya',
            name='count_sklad',
            field=models.IntegerField(default=0, help_text='Считается автоматом при создании накладных и заказов', verbose_name='Количество на складах'),
        ),
    ]
