# Generated by Django 2.2.6 on 2020-03-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_mtom_varstocons_count_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mtom_varstocons',
            options={'verbose_name': 'Позиция накладной', 'verbose_name_plural': 'Состав накладной'},
        ),
    ]
