# Generated by Django 2.2.2 on 2020-05-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200305_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default=0, upload_to='gallery/kollection'),
            preserve_default=False,
        ),
    ]
