# Generated by Django 2.2.6 on 2019-12-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0019_auto_20191222_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='fabricator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Название ООО или ИП или если частник, то просто ФИО', max_length=50, verbose_name='Наименование производителя')),
                ('slug', models.SlugField(blank=True, help_text='url адрес страницы производителя', max_length=200, unique=True)),
                ('address', models.CharField(help_text='Адрес в свободной форме (макс 100 символов)', max_length=100, verbose_name='Адрес места производства')),
                ('contacts', models.CharField(help_text='Контакты в свободной форме (макс 100 символов)', max_length=100, verbose_name='Контакты производителя')),
                ('data_create', models.DateField(auto_now_add=True, verbose_name='Дата создания производителя')),
                ('data_change', models.DateField(auto_now=True, verbose_name='Дата изменения производителя')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='consignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, help_text='Это поле соответствует номеру документа', max_length=25, verbose_name='Номер накладной')),
                ('data_doc', models.DateField(verbose_name='Дата документа')),
                ('responsible', models.CharField(help_text='ФИО ответственного за производство товара', max_length=50, verbose_name='Ответственнное лицо')),
                ('data_create', models.DateField(auto_now_add=True, verbose_name='Дата создания документа в системе')),
                ('data_change', models.DateField(auto_now=True, verbose_name='Дата изменения докумета в системе')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_consignments', to='app.Variaciya')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
                'ordering': ['-data_doc'],
            },
        ),
    ]
