# Generated by Django 2.2.6 on 2019-12-27 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='fabricator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='fabricator.fabricator'),
            preserve_default=False,
        ),
    ]
