# Generated by Django 2.2.6 on 2019-12-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0002_consignment_fabricator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='items',
        ),
    ]
