# Generated by Django 2.2.6 on 2020-01-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_variaciya_consignments'),
        ('fabricator', '0003_remove_consignment_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='variaciyi',
            field=models.ManyToManyField(related_name='consignments', to='app.Variaciya'),
        ),
    ]
