# Generated by Django 2.2.6 on 2020-01-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_variaciya_consignments'),
        ('fabricator', '0004_consignment_variaciyi'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='tovary',
            field=models.ManyToManyField(related_name='tovar_consignments', to='app.Tovar'),
        ),
    ]
