# Generated by Django 2.2.6 on 2020-01-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_variaciya_consignments'),
        ('fabricator', '0005_consignment_tovary'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='gallery',
            field=models.ManyToManyField(related_name='gallery_consignments', to='app.Gallery'),
        ),
    ]
