# Generated by Django 2.2.6 on 2020-01-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0006_consignment_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consignment',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='tovary',
        ),
        migrations.RemoveField(
            model_name='consignment',
            name='variaciyi',
        ),
    ]
