# Generated by Django 2.2.6 on 2020-03-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0007_auto_20200108_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='closed',
            field=models.BooleanField(default=False, help_text='Еслди документ закрыт, то он обрабатывается системой.', verbose_name='Документ закрыт'),
        ),
    ]
