# Generated by Django 2.2.6 on 2019-11-11 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20191111_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.TextField(verbose_name='Адрес доставки')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Дата обновления заявки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.StatusOrder')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
                'ordering': ('-date_create',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('count', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordervars', to='orders.Order')),
                ('variaciya', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_orders', to='app.Variaciya')),
            ],
            options={
                'verbose_name': 'Вариация товара из заявки',
                'verbose_name_plural': 'Вариации товаров из заявок',
            },
        ),
    ]
