# Generated by Django 2.2.6 on 2020-01-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200113_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='count_added',
            field=models.BooleanField(default=False, verbose_name='Учтено в подсчёте количества или нет?'),
        ),
    ]
